/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IPriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "checkedUpgrade" | "exec768" | "get1959"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkedUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "exec768", values?: undefined): string;
  encodeFunctionData(functionFragment: "get1959", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "checkedUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exec768", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get1959", data: BytesLike): Result;
}

export interface IPriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IPriceOracle;
  waitForDeployment(): Promise<this>;

  interface: IPriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkedUpgrade: TypedContractMethod<[data: BytesLike], [void], "nonpayable">;

  exec768: TypedContractMethod<[], [string], "payable">;

  get1959: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkedUpgrade"
  ): TypedContractMethod<[data: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exec768"
  ): TypedContractMethod<[], [string], "payable">;
  getFunction(
    nameOrSignature: "get1959"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
