/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as permit2 from './permit2/index.js';
export * as wormholeSoliditySdk from './wormhole-solidity-sdk/index.js';