/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wormholeSoliditySdk from './wormhole-solidity-sdk/index.js';
export type { wormholeSoliditySdk };