/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as permit2 from './permit2/index.js';
export type { permit2 };
import type * as wormholeSoliditySdk from './wormhole-solidity-sdk/index.js';
export type { wormholeSoliditySdk };