/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20.js';
export type { IERC20Metadata } from './IERC20Metadata.js';
export type { IERC20Permit } from './IERC20Permit.js';
export type { IWETH } from './IWETH.js';