# yarn zero install's "binary" can't describe references relative to the global cache reliably, so we disable it
enableGlobalCache: false

packageExtensions:
  "@wormhole-foundation/sdk-solana-tokenbridge@0.10.5":
    dependencies:
      bn.js: 5.1.2
  "@wormhole-foundation/sdk-solana-core@0.10.5":
    dependencies:
      bn.js: 5.1.2

yarnPath: .yarn/releases/yarn-4.4.1.cjs

npmPublishRegistry: "https://npm.pkg.github.com"
