# yarn zero install's "binary" can't describe references relative to the global cache reliably, so we disable it
enableGlobalCache: false

npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
  xlabs:
    npmRegistryServer: "https://npm.pkg.github.com"
  xlabs-xyz:
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.6.0.cjs
