# yarn zero install's "binary" can't describe references relative to the global cache reliably, so we disable it
enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.4.1.cjs

npmPublishRegistry: 'https://npm.pkg.github.com'
npmScopes:
  xlabs:
    npmRegistryServer: 'https://npm.pkg.github.com'

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux
  libc:
    - current
    - glibc
    - musl
