[toolchain]

[workspace]
members = ["solana/programs/*"]
types = "sdk/solana/tbrv3/idl"

[features]
resolution = true
skip-lint = true

[programs.localnet]
#token_bridge_relayer = "7TLiBkpDGshV4o3jmacTCx93CLkmo3VjZ111AsijN9f8"

[test]
upgradeable = true

#[[test.genesis]]
#address = "CefQJaxQTV28gCf4MMd1PgDHgCcRmuEHZgXZwjJReUY3"
#program = "../relayer-infra-contracts/src/solana/target/sbf-solana-solana/release/solana_price_oracle.so"

[[test.genesis]]
name = "wormhole-core"
address = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5" # Testnet in lib.rs
program = "solana/tests/bridge.so"                       # Wormhole Core program

[[test.genesis]]
name = "wormhole-bridge"
address = "DZnkkTmCiFWfYTfT41X3Rd1kDgozqzxWaHqsw6W4x2oe" # Testnet in lib.rs
program = "solana/tests/token_bridge.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./target/deploy/token_bridge_relayer-keypair.json"

[scripts]
setup-test = "cargo build-sbf -- -p solana-price-oracle --target-dir target"
test = "yarn run mocha -t 1000000 solana/tests/*.ts"
