[toolchain]

[workspace]
members = ["solana/programs/*"]
types = "sdk/solana/tbrv3/idl"

[features]
resolution = true
skip-lint = true

[programs.localnet]
solana = "46kv4wCpfEtLsHPDh4zm7jJb2pVdvke8Pj2ABYYJotFD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run tsc --build ./solana/tests/tsconfig.json && yarn run mocha -t 1000000 ts-build/solana-tests/*.js"
