[toolchain]

[workspace]
members = ["solana/programs/*"]
types = "sdk/solana/tbrv3/idl"

[features]
resolution = true
skip-lint = true

[programs.localnet]
token_bridge_relayer = "AttbEYJMSsnVRDcKY4AcX1GBcdPy9FzHcxTbKaMGGuLs"

[test]
upgradeable = true

[[test.genesis]]
address = "ATqjh2vkjogyVUUNmXQssQZNSFGgSA7Tm6P1UzEUg85s"
program = "lib/relayer-infra-contracts/src/solana/target/sbf-solana-solana/release/solana_price_oracle.so"

# [[test.genesis]]
# address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth" # Mainnet in lib.rs
# program = "solana/tests/bridge.so"                      # Wormhole Core program
#
# [[test.genesis]]
# address = "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb" # Mainnet in lib.rs
# program = "solana/tests/token_bridge.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./target/deploy/token_bridge_relayer-keypair.json"

[scripts]
setup-test = "cargo build-sbf -- -p solana-price-oracle"
test = "yarn ./solana build && yarn run mocha -t 1000000 solana/ts-build/tests/*.js"
