[toolchain]

[workspace]
members = ["solana/programs/*"]
types = "sdk/solana/tbrv3/idl"

[features]
resolution = true
skip-lint = true

[programs.localnet]
token_bridge_relayer = "AtTByoATABXxKRK8VZbiKw3vuURVszCpD5PmsgF6XXJc"

[[test.genesis]]
address = "ATqjh2vkjogyVUUNmXQssQZNSFGgSA7Tm6P1UzEUg85s" # Mainnet in lib.rs
program = "solana/tests/solana_price_oracle.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run mocha -p ./solana/tsconfig.json -t 1000000 solana/tests/token-bridge-relayer.ts"
test = "yarn ./solana build && yarn run mocha -t 1000000 solana/ts-build/tests/*.js"
