[profile.default]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
test = "test"
evm_version = "paris"
extra_output = ["metadata", "storageLayout", "evm.deployedBytecode.immutableReferences"]

out = 'build-forge'
libs = ['lib', 'node_modules', "../lib"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    "wormhole-sdk/=lib/wormhole-solidity-sdk/src/",
    "tbr/=src/",
    "price-oracle/=../lib/relayer-infra-contracts/apps/price-oracle/evm/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "permit2/=lib/permit2/src/interfaces/",
]

[fmt]
line_length = 100
multiline_func_header = "params_first"
# wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
