/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { RawDispatcher, RawDispatcherInterface } from "../RawDispatcher";

const _abi = [
  {
    type: "function",
    name: "exec768",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "get1959",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class RawDispatcher__factory {
  static readonly abi = _abi;
  static createInterface(): RawDispatcherInterface {
    return new Interface(_abi) as RawDispatcherInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RawDispatcher {
    return new Contract(address, _abi, runner) as unknown as RawDispatcher;
  }
}
