/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { TbrDispatcher, TbrDispatcherInterface } from "../../../src/assets/TbrDispatcher.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "chainId",
        "type": "uint16"
      }
    ],
    "name": "ChainIsNotRegistered",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "chainId",
        "type": "uint16"
      }
    ],
    "name": "ChainNotSupportedByTokenBridge",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "totalFee",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "FeeTooLarge",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "feeReceived",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "FeesInsufficient",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "maxGasDropoff",
        "type": "uint32"
      },
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "GasDropoffRequestedExceedsMaximum",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GasTokenNotSupported",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GasTokenOnlyAcceptedViaWithdrawal",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "IdempotentUpgrade",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "InsufficientGasDropoff",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "command",
        "type": "uint8"
      }
    ],
    "name": "InvalidAccessControlCommand",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "query",
        "type": "uint8"
      }
    ],
    "name": "InvalidAccessControlQuery",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "acquireMode",
        "type": "uint8"
      }
    ],
    "name": "InvalidAcquireMode",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidAddress",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "val",
        "type": "uint8"
      }
    ],
    "name": "InvalidBoolVal",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidChainId",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "command",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "InvalidCommand",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "command",
        "type": "uint8"
      }
    ],
    "name": "InvalidConfigCommand",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "query",
        "type": "uint8"
      }
    ],
    "name": "InvalidConfigQuery",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidData",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidImplementation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidMsgValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "version",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "InvalidMsgVersion",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSender",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTokenAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTokenRecipient",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "InvalidVaaLength",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "encodedLength",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expectedLength",
        "type": "uint256"
      }
    ],
    "name": "LengthMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "NotAnEvmAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotAuthorized",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "PaymentFailure",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PeerIsZeroAddress",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "targetChain",
        "type": "uint16"
      }
    ],
    "name": "TargetChainIsNotSupported",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "targetChain",
        "type": "uint16"
      }
    ],
    "name": "TransfersToChainArePaused",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "sourceChain",
        "type": "uint16"
      },
      {
        "internalType": "bytes32",
        "name": "sourceAddress",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "commandIndex",
        "type": "uint256"
      }
    ],
    "name": "UnrecognizedPeer",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "version",
        "type": "uint8"
      }
    ],
    "name": "UnsupportedVersion",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "revertData",
        "type": "bytes"
      }
    ],
    "name": "UpgradeFailed",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "addr",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isAdmin",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "AdminsUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "oldAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "newAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "FeeRecipienUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "oldAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "newAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "OwnerUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "sequence",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "gasDropoff",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "fee",
        "type": "uint256"
      }
    ],
    "name": "TransferRequested",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "Upgraded",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "cancelOwnershipTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "checkedUpgrade",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "exec768",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "get1959",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "receiveOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "upgrade",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  export class TbrDispatcher__factory {
    static readonly abi = _abi;
    static createInterface(): TbrDispatcherInterface {
      return new Interface(_abi) as TbrDispatcherInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): TbrDispatcher {
      return new Contract(address, _abi, runner) as unknown as TbrDispatcher;
    }
  }
  