/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assets from './assets/index.js';
export type { assets };
export type { Tbr } from './Tbr.js';