/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lib from './lib/index.js';
export type { lib };
import type * as src from './src/index.js';
export type { src };
export * as factories from './factories/index.js';
export type { Tbr } from './src/Tbr.js';
export { Tbr__factory } from './factories/src/Tbr__factory.js';
export type { Proxy } from './lib/wormhole-solidity-sdk/src/proxy/Proxy.js';
export { Proxy__factory } from './factories/lib/wormhole-solidity-sdk/src/proxy/Proxy__factory.js';